	
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: Roboto, Helvetica, Arial, sans-serif;
						font-size: 14px;
						color: #2f241d;
						background: #fffdf9;
					}
					table {
						border: none;
						border-collapse: collapse;
					}
					#sitemap{
						max-width: 100%;
						width: 100%;
					}
					#sitemap tr:nth-child(odd) td {
						background-color: #f7f2ec !important;
					}
					#sitemap tbody tr:hover td {
						background-color: #f3e7d7;
					}
					#sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
						color: #4f3a2a;
					}
					#content {
						margin: 0 auto;
						max-width: 1000px;
					}
					.company_name_title{
						color: #b08968;
					}
					.company_name_subtitle{
						color: #6f533d !important;
						font-size: 20px;
					}
					.company_name_subtitle:hover{
						color: #d2b48c !important;
						text-decoration: none;
					}
					.expl {
						margin: 18px 3px;
						line-height: 1.2em;
					}
					.expl a {
						color: #b08968;
						font-weight: 600;
					}
					.expl a:visited {
						color: #b08968;
					}
					a {
						color: #4f3a2a;
						text-decoration: none;
					}
					a:visited {
						color: #7a6556;
					}
					a:hover {
						text-decoration: underline;
					}
					td {
						font-size:14px;
						padding: 5px;
					}
					th {
						text-align:left;
						padding-right:30px;
						font-size:14px;
					}
					thead th {
						border-bottom: 1px solid #d8ccbf;
					}
				</style>
			</head>
			<body>
				<div id="content">
					<h1><span class="company_name_title">BelaYoga</span> Sitemap</h1>
					<p class="expl">
						Generated by 
						<a href="https://belayoga.space/" target="_blank" rel="noopener"  class="company_name_subtitle">
							BelaYoga
						</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>
						You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener">sitemaps.org</a>.
					</p>
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
						<p class="expl">
							This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
						</p>
						<table id="sitemap" cellpadding="3">
							<thead>
							<tr>
								<th width="75%">Sitemap</th>
								<th width="25%">Last Modified</th>
							</tr>
							</thead>
							<tbody>
							<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
								<xsl:variable name="sitemapURL">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<tr>
									<td>
										<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
									</td>
									<td>
										<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
									</td>
								</tr>
							</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
						<p class="expl">
							This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
						</p>
						<table id="sitemap" cellpadding="3">
							<thead>
							<tr>
								<th width="75%">URL</th>
								<th width="5%">Images</th>
								<th title="Last Modification Time" width="20%">Last Mod.</th>
							</tr>
							</thead>
							<tbody>
							<xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
							<xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<xsl:variable name="itemURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<a href="{$itemURL}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:value-of select="count(image:image)"/>
									</td>
									<td>
										<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
									</td>
								</tr>
							</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
